### ISSUE TITLE
GetCurrentTag implementation

### ISSUE THREAD

**Issue by shochdoerfer** [sebastianfeldmann/git#14]
I tried to get the information from a Git repository what the name of the latest tag is (assuming latest commit just got tagged). The GetCurrentTag implementation works fine in that case but returns weird tag names for untagged commits (the name of the latest tag incl. the commit hash of the latest commit). So I cannot really predict if a tag exists or not.

While doing some research I came across the command `git tag --points-at commit-sha`. Given the cli command won't return the current tag but the tag for a specific commit (and won't return anything if the commit is not tagged), would you want to include it in the package separately or would you look for a replacement of GetCurrentTag which might bring a BC break with it.

Looking forward to hear your thoughts!

**Comment by sebastianfeldmann** [comment]
Since I'm sure I have code that is relying on that "weird" behavior :) 
I think it is best to use a new method like get `getHeadTag` and then throw an Exception if no tag exists.

**Comment by shochdoerfer** [comment]
Sure, just realized I can find out the latest commit and then will build the magic around it. Feel free to close the issue then.

**Comment by sebastianfeldmann** [comment]
You can use `git tag --points-at HEAD` if you only want to look at the current one.

**Comment by sebastianfeldmann** [comment]
The `Info` operator now has a method `getTagsPointingTo` that returns a list of tags that are pointing to the given commit hash. So you could do something like this.

```php
$tags = $info->getTagsPointingTo('HEAD');

if (count($tags) < 1) {
    throw new NoTagException('current HEAD has no tag');
}
```
