### ISSUE TITLE
Bugs when staging multiple files for windows platform

### ISSUE THREAD

**Issue by blackpill** [sebastianfeldmann/git#19]
The following test code,
when only one file was staged, it works fine on both Linux and windows.
When more than one files were staged, it only works correctly on Linux.
On windows, it cannot output the staged file array.
```
<?php
use SebastianFeldmann\Git;

require __DIR__ . '/vendor/autoload.php';

// path to repository without .git
$repoRootPath  = __DIR__;
$gitRepository = new Git\Repository($repoRootPath);


// check the index status
$index = $gitRepository->getIndexOperator();
$files = $index->getStagedFiles();
var_dump($files);

```

My environment:
git: 2.25.0-64bit
windows 10 home edition

I found the multiple-line outputs of git use linux EOL, not windows EOL.
So, the following code cannot parse stdout to array.
> sebastianfeldmann/cli/src/Command/Result.php:188

**Comment by sebastianfeldmann** [comment]
I'm currently on the road, but will have a look at this asap

**Comment by sebastianfeldmann** [comment]
I updated the `cli` dependency (3.2.3) so it normalizes the line endings before splitting the lines up into an array.

This should fix your problem, please give it a try and let me know if it works

**Comment by blackpill** [comment]
It works now. Thank you!

**Comment by sebastianfeldmann** [comment]
Great, thanks for the feedback
