### ISSUE TITLE
Windows + PHP 7.4 - Log commands fail due to badly "sanitized" characters

### ISSUE THREAD

**Issue by Nessworthy** [sebastianfeldmann/git#33]
When using Windows, attempting to use the log operator to fetch commit information, I'm met with a load of simple xml parser errors.

I can trace these back to the command executed, to the format for `git log --pretty=format:"..."`
Without being escaped for shell arguments, it's this:
`<commit>%n<hash>%h</hash>%n<names><![CDATA[%d]]></names>%n<date>%ci</date>%n<author><![CDATA[%an]]></author>%n<subject><![CDATA[%s]]></subject>%n<body><![CDATA[%n%b%n]]></body>%n</commit>`

After escaping on windows, it becomes this:
`"<commit> n<hash> h</hash> n<names>< [CDATA[ d]]></names> n<date> ci</date> n<author>< [CDATA[ an]]></author> n<subject>< [CDATA[ s]]></subject> n<body>< [CDATA[ n b n]]></body> n</commit>"`

The `!` and `%` are stripped because of how overreaching the `escapeshellarg` function is. Is there any way to work around this safely?

**Comment by sebastianfeldmann** [comment]
I "fixed" the format escaping by doing some black custom voodoo if we are running on windows.

It worked on my Windows machine :)

So try to update to version 3.7.2 and let me know if it works.

#dontDoThisAtHomeKids

**Comment by Nessworthy** [comment]
Works like a charm!
