### ISSUE TITLE
\SebastianFeldmann\Git\Repository::isMerging() returns unexpected value after `cherry-pick -n`

### ISSUE THREAD

**Issue by worried-networking** [sebastianfeldmann/git#37]
Hello again :)

After I do a `git cherry-pick -n <commit>` the method `Repository::isMerging()` starts to return `true`, because there's a file `MERGE_MSG` in `.git` (and another file — `AUTO_MERGE`, don't know if it helps). This behaviour was a big surprise for me, and I'm unsure if it's expected/desired.

**Comment by sebastianfeldmann** [comment]
Thanks for the heads up.
Not sure it should work that way. I'll check and get back to you

**Comment by sebastianfeldmann** [comment]
So, if you are using the `-n` option git is not doing any commit, but it will merge the changes to your working directory and git will add all the merged changed to the index.

Git also creates a `MERGE_MSG` file storing the commit message of the cherry-picked commit.
So what you are doing is basically merging.

Do you have any issues with this behavior or was it just unexpected?

**Comment by worried-networking** [comment]
Thanks for digging into this!

I was more surprised, I think. I never expected that using `isMerging()` for ignoring the actions for merges could cause my code to skip the logic for something else.

I think I'll be fine if this behaviour is documented as expected.

**Comment by sebastianfeldmann** [comment]
I will add some more hints to the `PHPDoc`.
