### ISSUE TITLE
TypeError occurs while parsing git diff output containing "\ No newline at end of file"

### ISSUE THREAD

**Issue by Chemiker90** [sebastianfeldmann/git#38]
The _compare_ method of the Diff operator raises a TypeError if the output of the git diff command contains the line "\ No newline at end of file". It will be tried to parse as code change line, but the first char is only valid if '+', '-' or ' '. But the firstChar will not be validated, it will be used directly as key in a state map, where only the 3 mentioned entries are present. It results in a Undefined index Notice followed by a TypeError, because the receiving method only accepts string, not null.

**Comment by sebastianfeldmann** [comment]
I merged your pull request and tagged a new version (3.8.4).
Thanks for the fix :)
