### ISSUE TITLE
FilterByStatus OutputFormatter corrupts filenames

### ISSUE THREAD

**Issue by ktomk** [sebastianfeldmann/git#5]
**\SebastianFeldmann\Git\Command\DiffIndex\GetStagedFiles\FilterByStatus** corrupts filenames, including those that are common for git repositories.

This came to my attention when a `.gitignore` file was part of the changed files, but the formatter corrupted the filename into `gitignore` (that is w/o the leading dot).

**Comment by sebastianfeldmann** [comment]
Open issue, open pull request to fix issue... love it ;)
